image: registry.git.rwth-aachen.de/ths/smt/carl/ci:latest

#Gleicher Cache für alle Branches, Verschiedene für jeden Job
#Für alle Jobs der gleiche Cache klappt leider nicht, da diese bei verschiedenen Compilern neu compiliert werden müssen
cache: &global_cache
  key: ${CI_JOB_NAME}
  paths:
    - build/resources/
  policy: pull-push
#Für jeden Branch und jeden Job seperat -> Multiple Caches sind aus bzw. braucht gitlab 13.12
#Siehe https://gitlab.com/gitlab-org/gitlab/-/issues/32814#note_ca588f809e9dc92dbb3a55e2f3693be098b88a9d
#  key: "$CI_JOB_NAME-$CI_COMMIT_REF_SLUG"
#  paths: 
#    - build/*.so*
#    - build/*.a*
#  policy: pull-push


stages:
 # - tidy
  - build-gcc
  - build-clang 

make_tidy:
  stage: tidy
  script:
    - MAKE_PARALLEL=-j24 TASK=tidy source .ci/build.sh
  only:
    - ci-kroll

build-gcc10:
  stage: build-gcc
  script:
    - export CC=/usr/bin/gcc-10 && export CXX=/usr/bin/g++-10
    - MAKE_PARALLEL=-j12 TASK=parallel source .ci/build.sh
  only:
    - ci-kroll

build-gcc9:
  stage: build-gcc
  script:
    - export CC=/usr/bin/gcc-9 && export CXX=/usr/bin/g++-9
    - MAKE_PARALLEL=-j12 TASK=parallel source .ci/build.sh
  only:
    - ci-kroll
  
build-gcc8:
  stage: build-gcc
  script:
    - export CC=/usr/bin/gcc-8 && export CXX=/usr/bin/g++-8
    - MAKE_PARALLEL=-j12 TASK=parallel source .ci/build.sh
  only:
    - ci-kroll

build-clang11:
  stage: build-clang
  script:
     - export CC=/usr/bin/clang-11 && export CXX=/usr/bin/clang++-11
     - MAKE_PARALLEL=-j12 TASK=parallel source .ci/build.sh
  only:
    - ci-kroll

build-clang10:
  stage: build-clang
  script:
     - export CC=/usr/bin/clang-10 && export CXX=/usr/bin/clang++-10
     - MAKE_PARALLEL=-j12 TASK=parallel source .ci/build.sh
  only:
    - ci-kroll

build-clang9:
  stage: build-clang
  script:
     - export CC=/usr/bin/clang-9 && export CXX=/usr/bin/clang++-9
     - MAKE_PARALLEL=-j12 TASK=parallel source .ci/build.sh
  only:
    - ci-kroll