image: registry.git.rwth-aachen.de/ths/smt/carl/ci:latest

cache:
  key: ${CI_JOB_NAME}-$CI_COMMIT_REF_SLUG" #OVERRIDE
  paths:
    - build/resources/
  policy: pull-push
  #key: "$CI_JOB_NAME-$CI_COMMIT_REF_SLUG" #Verschieden für alle Branches und alle Jobs
  #paths: 
  #  - build/*.so*
  #  - build/*.a*
  #policy: pull-push

stages:
  - build
  - test
  - documentation

build-gcc12:
  dependencies: []
  stage: build
  script:
    - export CC=/usr/bin/gcc-12 && export CXX=/usr/bin/g++-12
    - MAKE_PARALLEL=-j8 TASK=all source .ci/build.sh
  artifacts: 
    name: "$CI_JOB_NAME-$CI_COMMIT_REF_SLUG"
    paths: 
      - build/
      - cmake/
      - src/
    expire_in: 1 week

.build-gcc11:
  dependencies: []
  stage: build
  script:
    - export CC=/usr/bin/gcc-11 && export CXX=/usr/bin/g++-11
    - MAKE_PARALLEL=-j8 TASK=all source .ci/build.sh
  artifacts: 
    name: "$CI_JOB_NAME-$CI_COMMIT_REF_SLUG"
    paths: 
      - build/
      - cmake/
      - src/
    expire_in: 1 week
  only:
     - development

build-clang14:
  dependencies: []
  stage: build
  script:
     - export CC=/usr/bin/clang-14 && export CXX=/usr/bin/clang++-14
     - MAKE_PARALLEL=-j8 TASK=all source .ci/build.sh
  artifacts: 
    name: "$CI_JOB_NAME-$CI_COMMIT_REF_SLUG"
    paths: 
      - build/
      - cmake/
      - src/
    expire_in: 1 week

.build-clang13:
  dependencies: []
  stage: build
  script:
     - export CC=/usr/bin/clang-13 && export CXX=/usr/bin/clang++-13
     - MAKE_PARALLEL=-j8 TASK=all source .ci/build.sh
  artifacts: 
    name: "$CI_JOB_NAME-$CI_COMMIT_REF_SLUG"
    paths: 
      - build/
      - cmake/
      - src/
    expire_in: 1 week
  only:
     - development

.test-clang: 
  dependencies: [build-clang14]
  stage: test
  script: 
    - cd build && make test

test-gcc: 
  dependencies: [build-gcc12]
  stage: test
  script: 
    - cd build && make test 

docs:
  stage: documentation
  cache: {}
  script:
    - MAKE_PARALLEL=-j4 TASK=documentation source .ci/build.sh
  only:
    - master


#### UNUSED ## 
#make_tidy:
#  stage: tidy
#  script:
#    - MAKE_PARALLEL=-j8 TASK=tidy source .ci/build.sh
