language: cpp

compiler:
  - gcc
  - clang

before_install:
  - sudo add-apt-repository -y ppa:kalakris/cmake
  - sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test
  - sudo add-apt-repository -y "deb http://llvm.org/apt/precise/ llvm-toolchain-precise-3.5 main"
  - sudo apt-get -qq update
# Install dependencies
  - sudo apt-get -qq install --force-yes clang-3.5 cmake g++-4.9 gcc-4.9 libboost-dev libcln-dev libeigen3-dev libgtest-dev
  - source ./.travis.flags


# Compile and run tests
script: mkdir build && cd build/ && cmake ../ && make resources && make -j4 && make test

notifications:
  email:
    on_failure: always
    on_success: change
