language: generic
sudo: false
dist: trusty

cache:
  apt: true

env:
  global:
    - secure: "mLSkH+V7W0F0GLxSgtJWUKlQu67aDdnvDpDIsR9n+1J0ECRDYcOpLa67OuILlYlZTYE84zEuQOPrRlldayPYdM5ZRRsdRHPrBukNB3kOPn2MsHh+xn2AGgaZduZMNgXpFDmkNOj8mkveJfKRjNcooYiQaXKJJXYjUrt3J+UTxUMBqfgdDHDHjCjPPviI1oxDVtbD15U6jcaKD7KdmLF+A1oHbZTlLbzhBP8JbQO4lJ28HVXBUZF+cjpDzlThHubB6KOhPB3CeVR1jwdcV1/HjYhWLNCFrui7EfjNl18hRsDdeFR0O77iJV6ktlzaccwamgUI+/SDk/2zrP2L7yf4hLtLjDbAxawDEVju+rrmPbHrvbS1D1iaYdJ4MqqKBja+hnQQueJFS4adYLNWKLgDHZwDFo6CFIeAIa+VE3xzh7/Qa+sXYRljqZlXuaFYL1Ra6+kRe5O3xztvwo2s8W59MjyQgwaR9YDzE7aXI6nyZH3ktqrbbTwVIUyTHt7qDFmuWo1YpHxI1Owwzgvn64t1zGD+Mo3pzGaZbJSlql0yC4bbMH47Ay6hRmsU4dwz8+R4o99xN+oJiBzebh7plkHpWlP5xzmjs3tAv51Afb6SLI3F45qm1qMj6x1T1tiq2d5GzWKDlz1URjhsCj6g1M8zOTj1mmFMqxvw2bHiy1gTIG4="

addons:
  apt:
    sources:
      - boost-latest
      - george-edison55-precise-backports
      - llvm-toolchain-precise
      - llvm-toolchain-precise-3.6
      - llvm-toolchain-precise-3.7
      - llvm-toolchain-precise-3.8
      - llvm-toolchain-trusty-3.9
      - llvm-toolchain-trusty-4.0
      - ubuntu-toolchain-r-test
    packages:
      - cmake
      - cmake-data
      - doxygen
      - lcov
      - libboost1.55-all-dev
      - libcln-dev
      - libeigen3-dev
      - libgmp-dev
      - libgtest-dev
      - g++-5
      - g++-6
      - clang-3.6
      - clang-3.7
      - clang-3.8
      - clang-3.9
      - clang-4.0
      - openjdk-7-jdk
      - time
      - texinfo
      - texlive

matrix:
  include:
    - os: linux
      env: USE=clang++-3.6
    - os: linux
      env: USE=clang++-3.7
    - os: linux
      env: USE=clang++-3.8
    - os: linux
      env: USE=clang++-3.9
    - os: linux
      env: USE=clang++-4.0
    - os: linux
      env: USE=g++-5
    - os: linux
      env: USE=g++-6
    - os: osx
      osx_image: xcode7.3
      env: USE=clang++-7.4
    - os: osx
      osx_image: xcode8.2
      env: USE=clang++-8.0
    - os: osx
      osx_image: xcode8.2
      env: USE=g++-5
    - os: osx
      osx_image: xcode8.2
      env: USE=g++-6
    - os: linux
      env: USE=g++-6 TASK=coverage
    - os: linux
      env: USE=g++-6 TASK=doxygen
    - os: linux
      env: USE=g++-6 TASK=pycarl
  allow_failures:
    - os: osx
      osx_image: xcode8.2
      env: USE=g++-5
    - os: osx
      osx_image: xcode8.2
      env: USE=g++-6
    - os: linux
      env: USE=g++-6 TASK=coverage
    - os: linux
      env: USE=g++-6 TASK=pycarl


before_install:
  - cd .travis/ && source setup_travis.sh && cd ../

script:
  - source .travis/build.sh

notifications:
  email:
    on_failure: always
    on_success: change
  irc:
    channels:
      - "chat.freenode.net#carl"
    template:
      - "Commit to %{repository_name}/%{branch} from %{author}"
      - "%{commit_message}"
      - "Build: %{message} %{duration} %{build_url}"
