language: generic
dist: bionic

cache:
  apt: true
  directories:
    - $HOME/usr/
    - $HOME/.sonar/cache
    - $HOME/build/smtrat/carl/build/resources

addons:
  apt:
    sources_base: &sources_base
      sourceline: 'ppa:ubuntu-toolchain-r/test'
    packages: &packages_base
      - texinfo
      - time
      - uuid-dev

jobs:
  include:
    - stage: dependencies
      os: linux
      compiler: g++-7
      env: CC=gcc-7 CXX=g++-7
      script: TASK=dependencies source .ci/build.sh
      addons:
        apt:
          sources:
          - *sources_base
          packages: [*packages_base, g++-7]
    - stage: dependencies
      os: linux
      compiler: g++-8
      env: CC=gcc-8 CXX=g++-8
      script: TASK=dependencies source .ci/build.sh
      addons:
        apt:
          sources:
          - *sources_base
          packages: [*packages_base, g++-8]
    - stage: dependencies
      os: linux
      compiler: g++-9
      env: CC=gcc-9 CXX=g++-9
      script: TASK=dependencies source .ci/build.sh
      addons:
        apt:
          sources:
          - *sources_base
          packages: [*packages_base, g++-9]
    - stage: dependencies
      os: linux
      compiler: clang++-9.0
      env: CC=clang-9 CXX=clang++-9 TASK=tidy
      script: TASK=dependencies source .ci/build.sh
      addons:
        apt:
          sources:
          - *sources_base
          - sourceline: 'deb http://apt.llvm.org/bionic/ llvm-toolchain-bionic-9 main'
            key_url: https://apt.llvm.org/llvm-snapshot.gpg.key
          packages: [*packages_base, clang-9, libstdc++-8-dev]
    - stage: dependencies
      os: linux
      compiler: clang++-9.0
      env: CC=clang-9 CXX=clang++-9 TASK=sonarcloud
      script: TASK=dependencies source .ci/build.sh
      cache:
        apt: true
        directories:
          - $HOME/usr/
          - $HOME/.sonar/cache
          - build/
          - bw-output/
      addons:
        apt:
          sources:
          - *sources_base
          - sourceline: 'deb http://apt.llvm.org/bionic/ llvm-toolchain-bionic-9 main'
            key_url: https://apt.llvm.org/llvm-snapshot.gpg.key
          packages: [*packages_base, clang-9, libstdc++-8-dev]
        sonarcloud:
          organization: "smtrat-github"
          token:
            secure: "nIGn6M7vkwD6HAKgS94QZIIU+A+dWOgqXzJ7lnAdGLXUx3cStVMO1LuOANttGyeGSJNj8Fa+YzwCx5EMQDvZW/b8cuoRld+I4gbmszUB6BXwQ6JJvpFczHrPpwyeo2LKrBN549aBCtOaLzw7rVPDzcdC6T39IvxpPXVCMTTjoq7Mp12HSWS8Ra8YIsOnJfYKVSxjCwcY9ICac70zpA6uKuWBNL13EBM+IpLACLFDKMcaIdb2CGyRvtbt7u8BOU9mjulRtpg1Ndc3eGEIIJJXM8lQTA+iMB6iapGWYbMB5Gwifrwy59UTgNbdR/6sWP5E5kxBGxn1lyp9VP6ChSS/b3Szhh0jUWaqBxoAK0Kh4KBeW7eeLvaUALuPmoNneGUZACrbNDq6aVzHUgwEKQTxF0reDkG3ZaEU+1NCukvLaI58OBxenb5bMOlEWzUMSMMuNO0MgVKXc3Nvr4oEm0USP6Ixky1AUTKTVDY87HHuQ+kCM/L5MQUQTwtQPuWF1zkDry+6A2LNABySla9AAtxlUth7rGvLwaTz2o3yMOIohQb12r8LqXnjESVcENk0f0gbyqeqM7aPcXAyqc6YDW9LBDSsWWa9SqxEfwz2zktzsWfKfCZWi4Fn7CaPdHGsGlSaGsXGovrT1DbyQPiTND0R1cinfrOqZBgwjWOB6JTol+g="
    - stage: dependencies
      os: linux
      compiler: g++-8
      env: CC=gcc-8 CXX=g++-8 TASK=pycarl
      script: TASK=dependencies MAKE_PARALLEL=-j1 source .ci/build.sh
      addons:
        apt:
          sources:
          - *sources_base
          packages: [*packages_base, g++-8, python3]
    - stage: dependencies
      os: linux
      compiler: g++-8
      env: CC=gcc-8 CXX=g++-8 TASK=addons
      script: TASK=dependencies MAKE_PARALLEL=-j1 source .ci/build.sh
      addons:
        apt:
          sources:
          - *sources_base
          packages: [*packages_base, g++-8]
    - stage: build
      os: linux
      compiler: clang++-5.0
      env: CC=clang-5.0 CXX=clang++-5.0
      script: source .ci/build.sh
      addons:
        apt:
          sources:
          - *sources_base
          packages: [*packages_base, clang-5.0]
    - stage: build
      os: linux
      compiler: clang++-6.0
      env: CC=clang-6.0 CXX=clang++-6.0
      script: source .ci/build.sh
      addons:
        apt:
          sources:
          - *sources_base
          packages: [*packages_base, clang-6.0]
    - stage: build
      os: linux
      compiler: clang++-7.0
      env: CC=clang-7 CXX=clang++-7
      script: source .ci/build.sh
      addons:
        apt:
          sources:
          - *sources_base
          - sourceline: 'deb http://apt.llvm.org/bionic/ llvm-toolchain-bionic main'
            key_url: https://apt.llvm.org/llvm-snapshot.gpg.key
          packages: [*packages_base, clang-7, libstdc++-8-dev]
    - stage: build
      os: linux
      compiler: clang++-8.0
      env: CC=clang-8 CXX=clang++-8
      script: source .ci/build.sh
      addons:
        apt:
          sources:
          - *sources_base
          - sourceline: 'deb http://apt.llvm.org/bionic/ llvm-toolchain-bionic-8 main'
            key_url: https://apt.llvm.org/llvm-snapshot.gpg.key
          packages: [*packages_base, clang-8, libstdc++-8-dev]
    - stage: build
      os: linux
      compiler: clang++-9.0
      env: CC=clang-9 CXX=clang++-9
      script: source .ci/build.sh
      addons:
        apt:
          sources:
          - *sources_base
          - sourceline: 'deb http://apt.llvm.org/bionic/ llvm-toolchain-bionic-9 main'
            key_url: https://apt.llvm.org/llvm-snapshot.gpg.key
          packages: [*packages_base, clang-9, libstdc++-8-dev]
    - stage: build
      os: linux
      compiler: g++-7
      env: CC=gcc-7 CXX=g++-7
      script: MAKE_PARALLEL=-j1 source .ci/build.sh
      addons:
        apt:
          sources:
          - *sources_base
          packages: [*packages_base, g++-7]
    - stage: build
      os: linux
      compiler: g++-8
      env: CC=gcc-8 CXX=g++-8
      script: MAKE_PARALLEL=-j1 source .ci/build.sh
      addons:
        apt:
          sources:
          - *sources_base
          packages: [*packages_base, g++-8]
    - stage: build
      os: linux
      compiler: g++-9
      env: CC=gcc-9 CXX=g++-9
      script: MAKE_PARALLEL=-j1 source .ci/build.sh
      addons:
        apt:
          sources:
          - *sources_base
          packages: [*packages_base, g++-9]
    - stage: build
      os: osx
      osx_image: xcode11
      script: source .ci/build.sh
    - stage: build
      os: osx
      osx_image: xcode11.1
      script: source .ci/build.sh
    - stage: build
      os: osx
      osx_image: xcode11.2
      script: source .ci/build.sh
    - stage: build
      os: linux
      compiler: g++-9
      env: CC=gcc-9 CXX=g++-9 TASK=documentation
      if: branch = master
      script: MAKE_PARALLEL=-j1 source .ci/build.sh
      addons:
        apt:
          sources:
          - *sources_base
          packages: [*packages_base, g++-9, ghostscript, graphviz, libclang-7-dev, lmodern, texinfo, texlive, texlive-font-utils, texlive-latex-extra, texlive-plain-generic, python3-pip, python3-setuptools]
    - stage: check
      os: linux
      compiler: clang++-9.0
      env: CC=clang-9 CXX=clang++-9 TASK=tidy
      script: source .ci/build.sh
      addons:
        apt:
          sources:
          - *sources_base
          - sourceline: 'deb http://apt.llvm.org/bionic/ llvm-toolchain-bionic-9 main'
            key_url: https://apt.llvm.org/llvm-snapshot.gpg.key
          packages: [*packages_base, clang-9, libstdc++-8-dev]
    - stage: build
      os: linux
      compiler: clang++-9.0
      env: CC=clang-9 CXX=clang++-9 TASK=sonarcloud
      script: TASK=sonarcloud-build source .ci/build.sh
      cache:
        apt: true
        directories:
          - $HOME/usr/
          - $HOME/.sonar/cache
          - build/
          - bw-output/
      addons:
        apt:
          sources:
          - *sources_base
          - sourceline: 'deb http://apt.llvm.org/bionic/ llvm-toolchain-bionic-9 main'
            key_url: https://apt.llvm.org/llvm-snapshot.gpg.key
          packages: [*packages_base, clang-9, libstdc++-8-dev]
        sonarcloud:
          organization: "smtrat-github"
          token:
            secure: "nIGn6M7vkwD6HAKgS94QZIIU+A+dWOgqXzJ7lnAdGLXUx3cStVMO1LuOANttGyeGSJNj8Fa+YzwCx5EMQDvZW/b8cuoRld+I4gbmszUB6BXwQ6JJvpFczHrPpwyeo2LKrBN549aBCtOaLzw7rVPDzcdC6T39IvxpPXVCMTTjoq7Mp12HSWS8Ra8YIsOnJfYKVSxjCwcY9ICac70zpA6uKuWBNL13EBM+IpLACLFDKMcaIdb2CGyRvtbt7u8BOU9mjulRtpg1Ndc3eGEIIJJXM8lQTA+iMB6iapGWYbMB5Gwifrwy59UTgNbdR/6sWP5E5kxBGxn1lyp9VP6ChSS/b3Szhh0jUWaqBxoAK0Kh4KBeW7eeLvaUALuPmoNneGUZACrbNDq6aVzHUgwEKQTxF0reDkG3ZaEU+1NCukvLaI58OBxenb5bMOlEWzUMSMMuNO0MgVKXc3Nvr4oEm0USP6Ixky1AUTKTVDY87HHuQ+kCM/L5MQUQTwtQPuWF1zkDry+6A2LNABySla9AAtxlUth7rGvLwaTz2o3yMOIohQb12r8LqXnjESVcENk0f0gbyqeqM7aPcXAyqc6YDW9LBDSsWWa9SqxEfwz2zktzsWfKfCZWi4Fn7CaPdHGsGlSaGsXGovrT1DbyQPiTND0R1cinfrOqZBgwjWOB6JTol+g="
    - stage: check
      os: linux
      compiler: clang++-9.0
      env: CC=clang-9 CXX=clang++-9 TASK=sonarcloud
      script: TASK=sonarcloud-scan source .ci/build.sh
      cache:
        apt: true
        directories:
          - $HOME/usr/
          - $HOME/.sonar/cache
          - build/
          - bw-output/
      addons:
        apt:
          sources:
          - *sources_base
          - sourceline: 'deb http://apt.llvm.org/bionic/ llvm-toolchain-bionic-9 main'
            key_url: https://apt.llvm.org/llvm-snapshot.gpg.key
          packages: [*packages_base, clang-9, libstdc++-8-dev]
        sonarcloud:
          organization: "smtrat-github"
          token:
            secure: "nIGn6M7vkwD6HAKgS94QZIIU+A+dWOgqXzJ7lnAdGLXUx3cStVMO1LuOANttGyeGSJNj8Fa+YzwCx5EMQDvZW/b8cuoRld+I4gbmszUB6BXwQ6JJvpFczHrPpwyeo2LKrBN549aBCtOaLzw7rVPDzcdC6T39IvxpPXVCMTTjoq7Mp12HSWS8Ra8YIsOnJfYKVSxjCwcY9ICac70zpA6uKuWBNL13EBM+IpLACLFDKMcaIdb2CGyRvtbt7u8BOU9mjulRtpg1Ndc3eGEIIJJXM8lQTA+iMB6iapGWYbMB5Gwifrwy59UTgNbdR/6sWP5E5kxBGxn1lyp9VP6ChSS/b3Szhh0jUWaqBxoAK0Kh4KBeW7eeLvaUALuPmoNneGUZACrbNDq6aVzHUgwEKQTxF0reDkG3ZaEU+1NCukvLaI58OBxenb5bMOlEWzUMSMMuNO0MgVKXc3Nvr4oEm0USP6Ixky1AUTKTVDY87HHuQ+kCM/L5MQUQTwtQPuWF1zkDry+6A2LNABySla9AAtxlUth7rGvLwaTz2o3yMOIohQb12r8LqXnjESVcENk0f0gbyqeqM7aPcXAyqc6YDW9LBDSsWWa9SqxEfwz2zktzsWfKfCZWi4Fn7CaPdHGsGlSaGsXGovrT1DbyQPiTND0R1cinfrOqZBgwjWOB6JTol+g="
    - stage: check
      os: linux
      compiler: clang++-9.0
      env: CC=clang-9 CXX=clang++-9 TASK=clang-ubsan
      script: source .ci/build.sh
      addons:
        apt:
          sources:
          - *sources_base
          - sourceline: 'deb http://apt.llvm.org/bionic/ llvm-toolchain-bionic-9 main'
            key_url: https://apt.llvm.org/llvm-snapshot.gpg.key
          packages: [*packages_base, clang-9, libstdc++-8-dev]
    - stage: build
      os: linux
      compiler: g++-8
      env: CC=gcc-8 CXX=g++-8 TASK=pycarl
      script: MAKE_PARALLEL=-j1 source .ci/build.sh
      addons:
        apt:
          sources:
          - *sources_base
          packages: [*packages_base, g++-8, python3]
    - stage: build
      os: linux
      compiler: g++-8
      env: CC=gcc-8 CXX=g++-8 TASK=addons
      script: MAKE_PARALLEL=-j1 source .ci/build.sh
      addons:
        apt:
          sources:
          - *sources_base
          packages: [*packages_base, g++-8]
  allow_failures:
    - stage: dependencies
      os: linux
      env: CC=clang-9 CXX=clang++-9 TASK=tidy
    - stage: dependencies
      os: linux
      env: CC=clang-9 CXX=clang++-9 TASK=sonarcloud
    - stage: build
      os: osx
      osx_image: xcode11
    - stage: build
      os: osx
      osx_image: xcode11.1
    - stage: build
      os: osx
      osx_image: xcode11.2
    - stage: check
      os: linux
      env: CC=clang-9 CXX=clang++-9 TASK=tidy
    - stage: build
      os: linux
      env: CC=clang-9 CXX=clang++-9 TASK=sonarcloud
    - stage: check
      os: linux
      env: CC=clang-9 CXX=clang++-9 TASK=sonarcloud
    - stage: check
      os: linux
      env: CC=clang-9 CXX=clang++-9 TASK=clang-ubsan
    - stage: build
      os: linux
      env: CC=gcc-8 CXX=g++-8 TASK=pycarl
    - stage: build
      os: linux
      env: CC=gcc-8 CXX=g++-8 TASK=addons

before_install:
  - cd .ci/ && source setup_travis.sh && cd ../

notifications:
  email:
    on_failure: always
    on_success: change
  slack:
    rooms:
      secure: "mL8Ku2omjsseTL5P2R2P3ddCedg8u9qSTKRjKNBhOYRJvpKNrIWr9fouP1tGsah9GBF+HL/JFWlA2sckCL9pURx6TdICHSgik1V/48QhpPKrV+ZkCmKenw3+hdXQY3YP36Xpj/SCCSMyRovA6kacWL3k0gRGJ++dxZYrYF7oVd8ltwxNC6+1o9HCmJnueCME5GBCKCgtOhYOr7izkjQ9wtFJvCmxHcI9EZxMQjWXmcHfItaWD1YFhR0/7AbsxJ9xtYZD0OMJrOgRBau671wV603a0EctIPcv0uKzjSsvB3yLndGOcMRsA8x/OPrFoOHbpLZ9d4O9gY3lvW5oueV+KTbbvHMSxJtvB9q3F0ZJSDHoG7cn1E2xb4gOHRdu4FhwqYy9abUM0DVUI/f7GaL+DMgzKeTduLB6h4GhtGR7fcWaBpCJYN1k8o33Vf/OPwaoPVCeiDRQIFqrqjDRcBc7ONe096WAf61albpMW6iCr5cBHy/j9XqEAGHu6sYftogWm/YVRqSF9+vnZy41cfQU+SYlFtWusUepqX1X/Kei+MCwESuddBnWj+oX8N8nreI8ql2IHG79IQVeEZZKMowxmo2IMsNnvkMyRTQsOmFY2u4NMRGga71QRCSbNvl01KxQ2ilyQ8Gu9Kjbs1QJ76jhOutChCzwOBAgc5aREdNCaV0="
