language: generic
sudo: false
dist: trusty

cache:
  apt: true
  directories:
    - $HOME/usr/
    - build/resources

_apt_packages:
  sources_boost: &sources_boost
    - boost-latest
  packages_boost: &packages_boost
    - libboost1.55-all-dev
  sources_cmake: &sources_cmake
    - george-edison55-precise-backports
  packages_cmake: &packages_cmake
    - cmake
    - cmake-data

addons:
  apt:
    sources: &sources_base
#      - *sources_boost
      - *sources_cmake
      - ubuntu-toolchain-r-test
    packages: &packages_base
#      - *packages_boost
      - *packages_cmake
      - g++-6
      - libcln-dev
      - libgmp-dev
      - libgtest-dev
      - openjdk-7-jdk
      - time
      - uuid-dev

matrix:
  include:
    - os: linux
      env: CC=clang-3.6 CXX=clang++-3.6
      addons:
        apt:
          sources: [*sources_base, llvm-toolchain-precise-3.6]
          packages: [*packages_base, clang-3.6]
    - os: linux
      env: CC=clang-3.7 CXX=clang++-3.7
      addons:
        apt:
          sources: [*sources_base, llvm-toolchain-precise-3.7]
          packages: [*packages_base, clang-3.7]
    - os: linux
      env: CC=clang-3.8 CXX=clang++-3.8
      addons:
        apt:
          sources: [*sources_base, llvm-toolchain-precise-3.8]
          packages: [*packages_base, clang-3.8]
    - os: linux
      env: CC=clang-3.9 CXX=clang++-3.9
      addons:
        apt:
          sources: [*sources_base, llvm-toolchain-trusty-3.9]
          packages: [*packages_base, clang-3.9]
    - os: linux
      env: CC=clang-4.0 CXX=clang++-4.0
      addons:
        apt:
          sources: [*sources_base, llvm-toolchain-trusty-4.0]
          packages: [*packages_base, clang-4.0]
    - os: linux
      env: CC=clang-5.0 CXX=clang++-5.0
      addons:
        apt:
          sources: [*sources_base, llvm-toolchain-trusty-5.0]
          packages: [*packages_base, clang-5.0]
    - os: linux
      env: CC=gcc-5 CXX=g++-5 MAKE_PARALLEL=-j1
      addons:
        apt:
          sources: [*sources_base]
          packages: [*packages_base, g++-5]
    - os: linux
      env: CC=gcc-6 CXX=g++-6 MAKE_PARALLEL=-j1
    - os: osx
      osx_image: xcode7.3
    - os: osx
      osx_image: xcode8.2
    - os: osx
      osx_image: xcode8.3
#    - os: osx
#      osx_image: xcode8.2
#      env: CC=gcc-5 CXX=g++-5
#    - os: osx
#      osx_image: xcode8.2
#      env: CC=gcc-6 CXX=g++-6
    - os: linux
      env: CC=gcc-6 CXX=g++-6 TASK=coverage MAKE_PARALLEL=-j1
      addons:
        apt:
          sources: [*sources_base]
          packages: [*packages_base, lcov]
    - os: linux
      env: CC=gcc-6 CXX=g++-6 TASK=doxygen MAKE_PARALLEL=-j1
      addons:
        apt:
          sources: [*sources_base]
          packages: [*packages_base, doxygen, texinfo, texlive]
    - os: linux
      env: CC=gcc-6 CXX=g++-6 TASK=pycarl MAKE_PARALLEL=-j1
      addons:
        apt:
          sources: [*sources_base]
          packages: [*packages_base, python3]
    - os: linux
      env: CC=gcc-6 CXX=g++-6 TASK=addons MAKE_PARALLEL=-j1
      addons:
        apt:
          sources: [*sources_base]
          packages: [*packages_base]
  allow_failures:
    - os: osx
      osx_image: xcode8.2
      env: CC=gcc-5 CXX=g++-5
    - os: osx
      osx_image: xcode8.2
      env: CC=gcc-6 CXX=g++-6
    - os: linux
      env: CC=gcc-6 CXX=g++-6 TASK=coverage MAKE_PARALLEL=-j1
    - os: linux
      env: CC=gcc-6 CXX=g++-6 TASK=pycarl MAKE_PARALLEL=-j1
    - os: linux
      env: CC=gcc-6 CXX=g++-6 TASK=addons MAKE_PARALLEL=-j1


before_install:
  - cd .ci/ && source setup_travis.sh && cd ../

script:
  - source .ci/build.sh

notifications:
  email:
    on_failure: always
    on_success: change
  irc:
    channels:
      - "chat.freenode.net#carl"
    template:
      - "Commit to %{repository_name}/%{branch} from %{author}"
      - "%{commit_message}"
      - "Build: %{message} %{duration} %{build_url}"
