language: generic
sudo: false
dist: trusty

cache:
  apt: true

env:
  global:
    - secure: "mLSkH+V7W0F0GLxSgtJWUKlQu67aDdnvDpDIsR9n+1J0ECRDYcOpLa67OuILlYlZTYE84zEuQOPrRlldayPYdM5ZRRsdRHPrBukNB3kOPn2MsHh+xn2AGgaZduZMNgXpFDmkNOj8mkveJfKRjNcooYiQaXKJJXYjUrt3J+UTxUMBqfgdDHDHjCjPPviI1oxDVtbD15U6jcaKD7KdmLF+A1oHbZTlLbzhBP8JbQO4lJ28HVXBUZF+cjpDzlThHubB6KOhPB3CeVR1jwdcV1/HjYhWLNCFrui7EfjNl18hRsDdeFR0O77iJV6ktlzaccwamgUI+/SDk/2zrP2L7yf4hLtLjDbAxawDEVju+rrmPbHrvbS1D1iaYdJ4MqqKBja+hnQQueJFS4adYLNWKLgDHZwDFo6CFIeAIa+VE3xzh7/Qa+sXYRljqZlXuaFYL1Ra6+kRe5O3xztvwo2s8W59MjyQgwaR9YDzE7aXI6nyZH3ktqrbbTwVIUyTHt7qDFmuWo1YpHxI1Owwzgvn64t1zGD+Mo3pzGaZbJSlql0yC4bbMH47Ay6hRmsU4dwz8+R4o99xN+oJiBzebh7plkHpWlP5xzmjs3tAv51Afb6SLI3F45qm1qMj6x1T1tiq2d5GzWKDlz1URjhsCj6g1M8zOTj1mmFMqxvw2bHiy1gTIG4="

_apt_packages:
  sources_boost: &sources_boost
    - boost-latest
  packages_boost: &packages_boost
    - libboost1.55-all-dev
  sources_cmake: &sources_cmake
    - george-edison55-precise-backports
  packages_cmake: &packages_cmake
    - cmake
    - cmake-data

addons:
  apt:
    sources: &sources_base
      - *sources_boost
      - *sources_cmake
      - ubuntu-toolchain-r-test
    packages: &packages_base
      - *packages_boost
      - *packages_cmake
      - g++-6
      - libcln-dev
      - libeigen3-dev
      - libgmp-dev
      - libgtest-dev
      - openjdk-7-jdk
      - time

matrix:
  include:
    - os: linux
      env: USE=clang++-3.6
      addons:
        apt:
          sources: [*sources_base, llvm-toolchain-precise-3.6]
          packages: [*packages_base, clang-3.6]
    - os: linux
      env: USE=clang++-3.7
      addons:
        apt:
          sources: [*sources_base, llvm-toolchain-precise-3.7]
          packages: [*packages_base, clang-3.7]
    - os: linux
      env: USE=clang++-3.8
      addons:
        apt:
          sources: [*sources_base, llvm-toolchain-precise-3.8]
          packages: [*packages_base, clang-3.8]
    - os: linux
      env: USE=clang++-3.9
      addons:
        apt:
          sources: [*sources_base, llvm-toolchain-trusty-3.9]
          packages: [*packages_base, clang-3.9]
    - os: linux
      env: USE=clang++-4.0
      addons:
        apt:
          sources: [*sources_base, llvm-toolchain-trusty-4.0]
          packages: [*packages_base, clang-4.0]
    - os: linux
      env: USE=g++-5
      addons:
        apt:
          sources: [*sources_base]
          packages: [*packages_base, g++-5]
    - os: linux
      env: USE=g++-6
    - os: osx
      osx_image: xcode7.3
      env: USE=clang++-7.4
    - os: osx
      osx_image: xcode8.2
      env: USE=clang++-8.0
    - os: osx
      osx_image: xcode8.3
      env: USE=clang++-8.1
    - os: osx
      osx_image: xcode8.2
      env: USE=g++-5
    - os: osx
      osx_image: xcode8.2
      env: USE=g++-6
    - os: linux
      env: USE=g++-6 TASK=coverage
      addons:
        apt:
          sources: [*sources_base]
          packages: [*packages_base, lcov]
    - os: linux
      env: USE=g++-6 TASK=doxygen
      addons:
        apt:
          sources: [*sources_base]
          packages: [*packages_base, doxygen, texinfo, texlive]
    - os: linux
      env: USE=g++-6 TASK=pycarl
  allow_failures:
    - os: osx
      osx_image: xcode8.2
      env: USE=g++-5
    - os: osx
      osx_image: xcode8.2
      env: USE=g++-6
    - os: linux
      env: USE=g++-6 TASK=coverage
    - os: linux
      env: USE=g++-6 TASK=pycarl


before_install:
  - cd .travis/ && source setup_travis.sh && cd ../

script:
  - source .travis/build.sh

notifications:
  email:
    on_failure: always
    on_success: change
  irc:
    channels:
      - "chat.freenode.net#carl"
    template:
      - "Commit to %{repository_name}/%{branch} from %{author}"
      - "%{commit_message}"
      - "Build: %{message} %{duration} %{build_url}"
