version: 1.0.{build}
image: Visual Studio 2017
environment:
  BOOST_ROOT: C:\Libraries\boost_1_64_0
  BOOST_LIBRARYDIR: C:\Libraries\boost_1_64_0\lib64-msvc-14.1
  CTEST_OUTPUT_ON_FAILURE: 1

cache:
  - C:\Libraries\mpir-3.0.0\ -> appveyor.xml

build_script:
  - call ".ci\setup_appveyor.cmd"
